// Countries Data with City Mappings
import { EUROPE_CITIES } from "./data-europe";
import { GLOBAL_CITIES } from "./data-global";
import { UK_CITIES } from "./data-uk";
import { US_CITIES } from "./data-us";
import { CityData, CountryData } from "./types";

// Group cities by country
function groupCitiesByCountry(cities: CityData[]): Record<string, CityData[]> {
  return cities.reduce((acc, city) => {
    const key = city.country;
    if (!acc[key]) acc[key] = [];
    acc[key].push(city);
    return acc;
  }, {} as Record<string, CityData[]>);
}

const allCities = [...US_CITIES, ...UK_CITIES, ...EUROPE_CITIES, ...GLOBAL_CITIES];
const citiesByCountry = groupCitiesByCountry(allCities);

export const COUNTRIES_DATA: CountryData[] = [
  {
    slug: "united-states",
    name: "United States",
    code: "US",
    currency: "USD",
    currencySymbol: "$",
    exchangeRateToUSD: 1,
    flagEmoji: "🇺🇸",
    region: "North America",
    description: "The US offers diverse living costs from expensive coastal cities to affordable Midwest and Southern metros.",
    cities: citiesByCountry["United States"] || [],
  },
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    code: "GB",
    currency: "GBP",
    currencySymbol: "£",
    exchangeRateToUSD: 1.27,
    flagEmoji: "🇬🇧",
    region: "Europe",
    description: "The UK offers diverse living costs, from expensive London to affordable northern cities.",
    cities: citiesByCountry["United Kingdom"] || [],
  },
  {
    slug: "canada",
    name: "Canada",
    code: "CA",
    currency: "CAD",
    currencySymbol: "C$",
    exchangeRateToUSD: 0.74,
    flagEmoji: "🇨🇦",
    region: "North America",
    description: "Canada offers high quality of life with universal healthcare.",
    cities: citiesByCountry["Canada"] || [],
  },
  {
    slug: "germany",
    name: "Germany",
    code: "DE",
    currency: "EUR",
    currencySymbol: "€",
    exchangeRateToUSD: 1.08,
    flagEmoji: "🇩🇪",
    region: "Europe",
    description: "Germany offers high living standards with excellent infrastructure and varied costs.",
    cities: citiesByCountry["Germany"] || [],
  },
  {
    slug: "netherlands",
    name: "Netherlands",
    code: "NL",
    currency: "EUR",
    currencySymbol: "€",
    exchangeRateToUSD: 1.08,
    flagEmoji: "🇳🇱",
    region: "Europe",
    description: "The Netherlands offers excellent quality of life with high salaries.",
    cities: citiesByCountry["Netherlands"] || [],
  },
  {
    slug: "france",
    name: "France",
    code: "FR",
    currency: "EUR",
    currencySymbol: "€",
    exchangeRateToUSD: 1.08,
    flagEmoji: "🇫🇷",
    region: "Europe",
    description: "France offers high quality of life with excellent healthcare and culture.",
    cities: citiesByCountry["France"] || [],
  },
  {
    slug: "spain",
    name: "Spain",
    code: "ES",
    currency: "EUR",
    currencySymbol: "€",
    exchangeRateToUSD: 1.08,
    flagEmoji: "🇪🇸",
    region: "Europe",
    description: "Spain offers excellent quality of life at lower costs with great weather.",
    cities: citiesByCountry["Spain"] || [],
  },
  {
    slug: "portugal",
    name: "Portugal",
    code: "PT",
    currency: "EUR",
    currencySymbol: "€",
    exchangeRateToUSD: 1.08,
    flagEmoji: "🇵🇹",
    region: "Europe",
    description: "Portugal is a hotspot for expats with affordable living and great weather.",
    cities: citiesByCountry["Portugal"] || [],
  },
  {
    slug: "switzerland",
    name: "Switzerland",
    code: "CH",
    currency: "CHF",
    currencySymbol: "CHF",
    exchangeRateToUSD: 1.12,
    flagEmoji: "🇨🇭",
    region: "Europe",
    description: "Switzerland has the highest salaries in Europe but also the highest costs.",
    cities: citiesByCountry["Switzerland"] || [],
  },
  {
    slug: "ireland",
    name: "Ireland",
    code: "IE",
    currency: "EUR",
    currencySymbol: "€",
    exchangeRateToUSD: 1.08,
    flagEmoji: "🇮🇪",
    region: "Europe",
    description: "Ireland hosts major tech companies with high salaries.",
    cities: citiesByCountry["Ireland"] || [],
  },
  {
    slug: "poland",
    name: "Poland",
    code: "PL",
    currency: "PLN",
    currencySymbol: "zł",
    exchangeRateToUSD: 0.25,
    flagEmoji: "🇵🇱",
    region: "Europe",
    description: "Poland offers low costs with rapidly growing tech scene.",
    cities: citiesByCountry["Poland"] || [],
  },
  {
    slug: "austria",
    name: "Austria",
    code: "AT",
    currency: "EUR",
    currencySymbol: "€",
    exchangeRateToUSD: 1.08,
    flagEmoji: "🇦🇹",
    region: "Europe",
    description: "Austria offers high quality of life with beautiful alpine scenery.",
    cities: citiesByCountry["Austria"] || [],
  },
  {
    slug: "czech-republic",
    name: "Czech Republic",
    code: "CZ",
    currency: "CZK",
    currencySymbol: "Kč",
    exchangeRateToUSD: 0.043,
    flagEmoji: "🇨🇿",
    region: "Europe",
    description: "Czech Republic offers affordable living with historic architecture.",
    cities: citiesByCountry["Czech Republic"] || [],
  },
  {
    slug: "hungary",
    name: "Hungary",
    code: "HU",
    currency: "HUF",
    currencySymbol: "Ft",
    exchangeRateToUSD: 0.0027,
    flagEmoji: "🇭🇺",
    region: "Europe",
    description: "Hungary offers very affordable living with beautiful architecture.",
    cities: citiesByCountry["Hungary"] || [],
  },
  {
    slug: "sweden",
    name: "Sweden",
    code: "SE",
    currency: "SEK",
    currencySymbol: "kr",
    exchangeRateToUSD: 0.095,
    flagEmoji: "🇸🇪",
    region: "Europe",
    description: "Sweden offers excellent quality of life with high living standards.",
    cities: citiesByCountry["Sweden"] || [],
  },
  {
    slug: "denmark",
    name: "Denmark",
    code: "DK",
    currency: "DKK",
    currencySymbol: "kr",
    exchangeRateToUSD: 0.145,
    flagEmoji: "🇩🇰",
    region: "Europe",
    description: "Denmark offers one of the highest qualities of life in the world.",
    cities: citiesByCountry["Denmark"] || [],
  },
  {
    slug: "united-arab-emirates",
    name: "United Arab Emirates",
    code: "AE",
    currency: "AED",
    currencySymbol: "د.إ",
    exchangeRateToUSD: 0.27,
    flagEmoji: "🇦🇪",
    region: "Middle East",
    description: "The UAE offers tax-free salaries with high living standards.",
    cities: citiesByCountry["United Arab Emirates"] || [],
  },
  {
    slug: "singapore",
    name: "Singapore",
    code: "SG",
    currency: "SGD",
    currencySymbol: "S$",
    exchangeRateToUSD: 0.74,
    flagEmoji: "🇸🇬",
    region: "Asia",
    description: "Singapore is Asia's financial hub with low taxes.",
    cities: citiesByCountry["Singapore"] || [],
  },
  {
    slug: "australia",
    name: "Australia",
    code: "AU",
    currency: "AUD",
    currencySymbol: "A$",
    exchangeRateToUSD: 0.65,
    flagEmoji: "🇦🇺",
    region: "Oceania",
    description: "Australia offers high salaries and outdoor lifestyle.",
    cities: citiesByCountry["Australia"] || [],
  },
];
