// European Cities Cost of Living Data
import { CityData } from "./types";

export const EUROPE_CITIES: CityData[] = [
  // Germany
  {
    slug: "munich",
    name: "Munich",
    country: "Germany",
    countryCode: "DE",
    population: 1472000,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 95,
    rentIndex: 92,
    groceriesIndex: 88,
    restaurantsIndex: 85,
    transportIndex: 95,
    utilitiesIndex: 105,
    childcareIndex: 110,
    healthcareIndex: 92,
    averageNetSalary: 3600,
    averageNetSalaryUSD: 3096,
    medianNetSalary: 3200,
    description: "Munich is Germany's most expensive city but offers exceptional quality of life.",
    highlights: ["Highest salaries in Germany", "Excellent transport", "Beer culture", "Alps access"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 92,
      sources: [
        { name: "Eurostat", reliability: 95 },
        { name: "Numbeo", reliability: 88 },
        { name: "German Federal Statistical Office", reliability: 93 }
      ],
      sampleSize: 6800,
      confidence: 90
    },
    qualityOfLifeIndex: 85,
    safetyIndex: 88
  },
  {
    slug: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    population: 3645000,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 78,
    rentIndex: 68,
    groceriesIndex: 82,
    restaurantsIndex: 75,
    transportIndex: 88,
    utilitiesIndex: 98,
    childcareIndex: 85,
    healthcareIndex: 88,
    averageNetSalary: 3000,
    averageNetSalaryUSD: 2580,
    medianNetSalary: 2700,
    description: "Berlin offers affordable European capital living with vibrant startup scene.",
    highlights: ["Startup hub", "Affordable capital", "Best nightlife", "Creative industries"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 89,
      sources: [
        { name: "Eurostat", reliability: 93 },
        { name: "Numbeo", reliability: 85 },
        { name: "German Federal Statistical Office", reliability: 90 }
      ],
      sampleSize: 8200,
      confidence: 87
    },
    qualityOfLifeIndex: 80,
    safetyIndex: 82
  },
  {
    slug: "frankfurt",
    name: "Frankfurt",
    country: "Germany",
    countryCode: "DE",
    population: 753056,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 88,
    rentIndex: 82,
    groceriesIndex: 85,
    restaurantsIndex: 82,
    transportIndex: 92,
    utilitiesIndex: 102,
    childcareIndex: 95,
    healthcareIndex: 90,
    averageNetSalary: 3800,
    averageNetSalaryUSD: 3268,
    medianNetSalary: 3400,
    description: "Frankfurt is the financial capital of continental Europe.",
    highlights: ["Financial hub", "High salaries", "International airport", "Central location"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 90,
      sources: [
        { name: "Eurostat", reliability: 94 },
        { name: "Numbeo", reliability: 86 },
        { name: "German Federal Statistical Office", reliability: 91 }
      ],
      sampleSize: 5200,
      confidence: 88
    },
    qualityOfLifeIndex: 82,
    safetyIndex: 85
  },
  // Netherlands
  {
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    population: 872680,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 98,
    rentIndex: 105,
    groceriesIndex: 88,
    restaurantsIndex: 95,
    transportIndex: 92,
    utilitiesIndex: 110,
    childcareIndex: 115,
    healthcareIndex: 94,
    averageNetSalary: 3400,
    averageNetSalaryUSD: 2924,
    medianNetSalary: 3100,
    description: "Amsterdam combines Dutch efficiency with international flair.",
    highlights: ["Cycling paradise", "International workforce", "Tech hub", "Canal lifestyle"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 91,
      sources: [
        { name: "Eurostat", reliability: 94 },
        { name: "Numbeo", reliability: 87 },
        { name: "Dutch Central Bureau of Statistics", reliability: 92 }
      ],
      sampleSize: 5800,
      confidence: 89
    },
    qualityOfLifeIndex: 83,
    safetyIndex: 86
  },
  {
    slug: "rotterdam",
    name: "Rotterdam",
    country: "Netherlands",
    countryCode: "NL",
    population: 651446,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 82,
    rentIndex: 78,
    groceriesIndex: 85,
    restaurantsIndex: 82,
    transportIndex: 88,
    utilitiesIndex: 105,
    childcareIndex: 90,
    healthcareIndex: 89,
    averageNetSalary: 3100,
    averageNetSalaryUSD: 2666,
    medianNetSalary: 2800,
    description: "Rotterdam offers modern architecture and more affordable alternative to Amsterdam.",
    highlights: ["Modern architecture", "Lower costs", "Major port", "Innovative culture"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 87,
      sources: [
        { name: "Eurostat", reliability: 92 },
        { name: "Numbeo", reliability: 84 },
        { name: "Dutch Central Bureau of Statistics", reliability: 89 }
      ],
      sampleSize: 4200,
      confidence: 85
    },
    qualityOfLifeIndex: 78,
    safetyIndex: 81
  },
  // France
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    countryCode: "FR",
    population: 2161000,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 105,
    rentIndex: 115,
    groceriesIndex: 92,
    restaurantsIndex: 98,
    transportIndex: 88,
    utilitiesIndex: 95,
    childcareIndex: 108,
    healthcareIndex: 91,
    averageNetSalary: 3100,
    averageNetSalaryUSD: 2666,
    medianNetSalary: 2800,
    description: "Paris is one of Europe's most expensive cities with unmatched culture.",
    highlights: ["Cultural capital", "Fashion industry", "Amazing food", "Historic architecture"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 93,
      sources: [
        { name: "Eurostat", reliability: 95 },
        { name: "Numbeo", reliability: 89 },
        { name: "INSEE", reliability: 94 }
      ],
      sampleSize: 7200,
      confidence: 91
    },
    qualityOfLifeIndex: 81,
    safetyIndex: 79
  },
  {
    slug: "lyon",
    name: "Lyon",
    country: "France",
    countryCode: "FR",
    population: 516092,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 78,
    rentIndex: 65,
    groceriesIndex: 88,
    restaurantsIndex: 82,
    transportIndex: 82,
    utilitiesIndex: 90,
    childcareIndex: 85,
    healthcareIndex: 86,
    averageNetSalary: 2600,
    averageNetSalaryUSD: 2236,
    medianNetSalary: 2350,
    description: "Lyon is France's gastronomic capital with lower costs than Paris.",
    highlights: ["Food capital", "Much cheaper than Paris", "Rich history", "Central location"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 86,
      sources: [
        { name: "Eurostat", reliability: 90 },
        { name: "Numbeo", reliability: 82 },
        { name: "INSEE", reliability: 88 }
      ],
      sampleSize: 3800,
      confidence: 84
    },
    qualityOfLifeIndex: 77,
    safetyIndex: 80
  },
  // Spain
  {
    slug: "madrid",
    name: "Madrid",
    country: "Spain",
    countryCode: "ES",
    population: 3223000,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 68,
    rentIndex: 58,
    groceriesIndex: 72,
    restaurantsIndex: 65,
    transportIndex: 75,
    utilitiesIndex: 82,
    childcareIndex: 75,
    healthcareIndex: 83,
    averageNetSalary: 2300,
    averageNetSalaryUSD: 1978,
    medianNetSalary: 2100,
    description: "Madrid offers affordable European capital living with excellent climate.",
    highlights: ["Affordable capital", "Great weather", "Nightlife", "Central location"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 85,
      sources: [
        { name: "Eurostat", reliability: 89 },
        { name: "Numbeo", reliability: 81 },
        { name: "INE", reliability: 87 }
      ],
      sampleSize: 6200,
      confidence: 83
    },
    qualityOfLifeIndex: 76,
    safetyIndex: 78
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    population: 1620343,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 72,
    rentIndex: 65,
    groceriesIndex: 75,
    restaurantsIndex: 68,
    transportIndex: 78,
    utilitiesIndex: 85,
    childcareIndex: 78,
    healthcareIndex: 84,
    averageNetSalary: 2200,
    averageNetSalaryUSD: 1892,
    medianNetSalary: 2000,
    description: "Barcelona combines beach lifestyle with tech industry growth.",
    highlights: ["Beach city", "Tech hub", "Digital nomad friendly", "Mediterranean cuisine"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 86,
      sources: [
        { name: "Eurostat", reliability: 90 },
        { name: "Numbeo", reliability: 82 },
        { name: "INE", reliability: 88 }
      ],
      sampleSize: 5400,
      confidence: 84
    },
    qualityOfLifeIndex: 79,
    safetyIndex: 77
  },
  {
    slug: "valencia",
    name: "Valencia",
    country: "Spain",
    countryCode: "ES",
    population: 791413,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 58,
    rentIndex: 42,
    groceriesIndex: 68,
    restaurantsIndex: 58,
    transportIndex: 70,
    utilitiesIndex: 78,
    childcareIndex: 65,
    healthcareIndex: 80,
    averageNetSalary: 1900,
    averageNetSalaryUSD: 1634,
    medianNetSalary: 1750,
    description: "Valencia offers one of Europe's best quality of life to cost ratios.",
    highlights: ["Very affordable", "Beach lifestyle", "Great weather", "Paella origin"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 83,
      sources: [
        { name: "Eurostat", reliability: 87 },
        { name: "Numbeo", reliability: 79 },
        { name: "INE", reliability: 85 }
      ],
      sampleSize: 3200,
      confidence: 81
    },
    qualityOfLifeIndex: 82,
    safetyIndex: 79
  },
  // Portugal
  {
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    population: 544851,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 62,
    rentIndex: 55,
    groceriesIndex: 65,
    restaurantsIndex: 55,
    transportIndex: 70,
    utilitiesIndex: 78,
    childcareIndex: 68,
    healthcareIndex: 77,
    averageNetSalary: 1600,
    averageNetSalaryUSD: 1376,
    medianNetSalary: 1450,
    description: "Lisbon offers old-world charm with modern startup culture at affordable prices.",
    highlights: ["Startup hub", "Digital nomad visa", "Great weather", "Historic beauty"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 84,
      sources: [
        { name: "Eurostat", reliability: 88 },
        { name: "Numbeo", reliability: 80 },
        { name: "INE Portugal", reliability: 86 }
      ],
      sampleSize: 3600,
      confidence: 82
    },
    qualityOfLifeIndex: 78,
    safetyIndex: 81
  },
  {
    slug: "porto",
    name: "Porto",
    country: "Portugal",
    countryCode: "PT",
    population: 237591,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 52,
    rentIndex: 42,
    groceriesIndex: 62,
    restaurantsIndex: 48,
    transportIndex: 65,
    utilitiesIndex: 72,
    childcareIndex: 58,
    healthcareIndex: 74,
    averageNetSalary: 1400,
    averageNetSalaryUSD: 1204,
    medianNetSalary: 1300,
    description: "Porto offers more affordable living than Lisbon with growing tech scene.",
    highlights: ["Very affordable", "Port wine", "Beautiful riverfront", "Growing tech scene"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 81,
      sources: [
        { name: "Eurostat", reliability: 85 },
        { name: "Numbeo", reliability: 77 },
        { name: "INE Portugal", reliability: 83 }
      ],
      sampleSize: 2400,
      confidence: 79
    },
    qualityOfLifeIndex: 75,
    safetyIndex: 78
  },
  // Switzerland
  {
    slug: "zurich",
    name: "Zurich",
    country: "Switzerland",
    countryCode: "CH",
    population: 421878,
    currency: "CHF",
    currencySymbol: "CHF",
    costIndex: 145,
    rentIndex: 165,
    groceriesIndex: 135,
    restaurantsIndex: 150,
    transportIndex: 130,
    utilitiesIndex: 120,
    childcareIndex: 140,
    healthcareIndex: 110,
    averageNetSalary: 7000,
    averageNetSalaryUSD: 6230,
    medianNetSalary: 6500,
    description: "Zurich is one of the world's most expensive cities but offers exceptional salaries.",
    highlights: ["Highest salaries globally", "Excellent quality of life", "Safe city", "Lake lifestyle"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 94,
      sources: [
        { name: "Swiss Federal Statistical Office", reliability: 96 },
        { name: "Numbeo", reliability: 90 },
        { name: "Eurostat", reliability: 92 }
      ],
      sampleSize: 4200,
      confidence: 92
    },
    qualityOfLifeIndex: 88,
    safetyIndex: 92
  },
  {
    slug: "geneva",
    name: "Geneva",
    country: "Switzerland",
    countryCode: "CH",
    population: 201818,
    currency: "CHF",
    currencySymbol: "CHF",
    costIndex: 148,
    rentIndex: 170,
    groceriesIndex: 138,
    restaurantsIndex: 155,
    transportIndex: 135,
    utilitiesIndex: 122,
    childcareIndex: 145,
    healthcareIndex: 115,
    averageNetSalary: 7200,
    averageNetSalaryUSD: 6408,
    medianNetSalary: 6800,
    description: "Geneva hosts international organizations with stunning Alpine views.",
    highlights: ["UN & international orgs", "French-speaking", "Lake Geneva views", "Luxury lifestyle"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 93,
      sources: [
        { name: "Swiss Federal Statistical Office", reliability: 95 },
        { name: "Numbeo", reliability: 89 },
        { name: "Eurostat", reliability: 91 }
      ],
      sampleSize: 2800,
      confidence: 91
    },
    qualityOfLifeIndex: 86,
    safetyIndex: 90
  },
  // Ireland
  {
    slug: "dublin",
    name: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    population: 544107,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 98,
    rentIndex: 115,
    groceriesIndex: 92,
    restaurantsIndex: 95,
    transportIndex: 88,
    utilitiesIndex: 95,
    childcareIndex: 105,
    healthcareIndex: 89,
    averageNetSalary: 3800,
    averageNetSalaryUSD: 3268,
    medianNetSalary: 3400,
    description: "Dublin hosts European HQs of major tech companies with high salaries.",
    highlights: ["Tech hub", "Google & Facebook HQs", "English-speaking", "Friendly culture"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 90,
      sources: [
        { name: "Central Statistics Office Ireland", reliability: 92 },
        { name: "Numbeo", reliability: 85 },
        { name: "Eurostat", reliability: 88 }
      ],
      sampleSize: 4800,
      confidence: 88
    },
    qualityOfLifeIndex: 79,
    safetyIndex: 83
  },
  // Poland
  {
    slug: "warsaw",
    name: "Warsaw",
    country: "Poland",
    countryCode: "PL",
    population: 1790658,
    currency: "PLN",
    currencySymbol: "zł",
    costIndex: 48,
    rentIndex: 38,
    groceriesIndex: 45,
    restaurantsIndex: 42,
    transportIndex: 52,
    utilitiesIndex: 55,
    childcareIndex: 50,
    healthcareIndex: 60,
    averageNetSalary: 8000,
    averageNetSalaryUSD: 1600,
    medianNetSalary: 7200,
    description: "Warsaw is a rapidly growing tech hub with very low costs.",
    highlights: ["Growing tech hub", "Very affordable", "Modern infrastructure", "Central Europe"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 85,
      sources: [
        { name: "GUS", reliability: 87 },
        { name: "Numbeo", reliability: 79 },
        { name: "Eurostat", reliability: 84 }
      ],
      sampleSize: 5200,
      confidence: 83
    },
    qualityOfLifeIndex: 73,
    safetyIndex: 76
  },
  {
    slug: "krakow",
    name: "Krakow",
    country: "Poland",
    countryCode: "PL",
    population: 779115,
    currency: "PLN",
    currencySymbol: "zł",
    costIndex: 42,
    rentIndex: 32,
    groceriesIndex: 42,
    restaurantsIndex: 38,
    transportIndex: 48,
    utilitiesIndex: 52,
    childcareIndex: 45,
    healthcareIndex: 55,
    averageNetSalary: 7000,
    averageNetSalaryUSD: 1400,
    medianNetSalary: 6500,
    description: "Krakow offers historic charm with growing IT industry at low costs.",
    highlights: ["Beautiful old town", "Very low costs", "IT outsourcing hub", "Student city"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 82,
      sources: [
        { name: "GUS", reliability: 84 },
        { name: "Numbeo", reliability: 76 },
        { name: "Eurostat", reliability: 81 }
      ],
      sampleSize: 3800,
      confidence: 80
    },
    qualityOfLifeIndex: 71,
    safetyIndex: 74
  },
  // New additions - missing major European cities
  {
    slug: "vienna",
    name: "Vienna",
    country: "Austria",
    countryCode: "AT",
    population: 1911191,
    currency: "EUR",
    currencySymbol: "€",
    costIndex: 82,
    rentIndex: 72,
    groceriesIndex: 85,
    restaurantsIndex: 78,
    transportIndex: 85,
    utilitiesIndex: 88,
    childcareIndex: 80,
    healthcareIndex: 85,
    averageNetSalary: 3200,
    averageNetSalaryUSD: 2752,
    medianNetSalary: 2900,
    description: "Vienna consistently ranks as one of the world's most livable cities.",
    highlights: ["Most livable city", "Cultural capital", "Excellent public transport", "Coffee culture"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 91,
      sources: [
        { name: "Statistics Austria", reliability: 93 },
        { name: "Numbeo", reliability: 86 },
        { name: "Eurostat", reliability: 90 }
      ],
      sampleSize: 5800,
      confidence: 89
    },
    qualityOfLifeIndex: 87,
    safetyIndex: 88
  },
  {
    slug: "prague",
    name: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    population: 1324277,
    currency: "CZK",
    currencySymbol: "Kč",
    costIndex: 55,
    rentIndex: 42,
    groceriesIndex: 58,
    restaurantsIndex: 52,
    transportIndex: 60,
    utilitiesIndex: 65,
    childcareIndex: 55,
    healthcareIndex: 70,
    averageNetSalary: 55000,
    averageNetSalaryUSD: 1850,
    medianNetSalary: 50000,
    description: "Prague offers fairy-tale architecture with growing tech sector at affordable costs.",
    highlights: ["Fairy-tale architecture", "Growing tech hub", "Beer capital", "Affordable living"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 86,
      sources: [
        { name: "Czech Statistical Office", reliability: 88 },
        { name: "Numbeo", reliability: 80 },
        { name: "Eurostat", reliability: 85 }
      ],
      sampleSize: 4200,
      confidence: 84
    },
    qualityOfLifeIndex: 77,
    safetyIndex: 80
  },
  {
    slug: "budapest",
    name: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    population: 1752286,
    currency: "HUF",
    currencySymbol: "Ft",
    costIndex: 45,
    rentIndex: 35,
    groceriesIndex: 48,
    restaurantsIndex: 42,
    transportIndex: 52,
    utilitiesIndex: 58,
    childcareIndex: 48,
    healthcareIndex: 62,
    averageNetSalary: 650000,
    averageNetSalaryUSD: 1350,
    medianNetSalary: 580000,
    description: "Budapest offers stunning architecture and thermal baths at very low costs.",
    highlights: ["Thermal baths", "Beautiful architecture", "Very affordable", "Growing startup scene"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 83,
      sources: [
        { name: "Hungarian Central Statistical Office", reliability: 85 },
        { name: "Numbeo", reliability: 77 },
        { name: "Eurostat", reliability: 82 }
      ],
      sampleSize: 3600,
      confidence: 81
    },
    qualityOfLifeIndex: 74,
    safetyIndex: 75
  },
  {
    slug: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    population: 980971,
    currency: "SEK",
    currencySymbol: "kr",
    costIndex: 108,
    rentIndex: 115,
    groceriesIndex: 95,
    restaurantsIndex: 102,
    transportIndex: 98,
    utilitiesIndex: 105,
    childcareIndex: 95,
    healthcareIndex: 88,
    averageNetSalary: 38000,
    averageNetSalaryUSD: 2850,
    medianNetSalary: 34000,
    description: "Stockholm offers Scandinavian design and innovation at high costs.",
    highlights: ["Innovation hub", "Beautiful archipelago", "Design capital", "High quality of life"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 89,
      sources: [
        { name: "Statistics Sweden", reliability: 91 },
        { name: "Numbeo", reliability: 83 },
        { name: "Eurostat", reliability: 88 }
      ],
      sampleSize: 4800,
      confidence: 87
    },
    qualityOfLifeIndex: 84,
    safetyIndex: 86
  },
  {
    slug: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    population: 638117,
    currency: "DKK",
    currencySymbol: "kr",
    costIndex: 112,
    rentIndex: 120,
    groceriesIndex: 98,
    restaurantsIndex: 105,
    transportIndex: 95,
    utilitiesIndex: 108,
    childcareIndex: 92,
    healthcareIndex: 86,
    averageNetSalary: 42000,
    averageNetSalaryUSD: 2940,
    medianNetSalary: 38000,
    description: "Copenhagen offers hygge lifestyle and sustainable design at premium costs.",
    highlights: ["Sustainable design", "Bike-friendly", "Happy residents", "Nordic cuisine"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 90,
      sources: [
        { name: "Statistics Denmark", reliability: 92 },
        { name: "Numbeo", reliability: 84 },
        { name: "Eurostat", reliability: 89 }
      ],
      sampleSize: 4200,
      confidence: 88
    },
    qualityOfLifeIndex: 86,
    safetyIndex: 87
  }
];