// Global Cities Cost of Living Data (Americas, Asia, Middle East, Oceania)
import { CityData } from "./types";

export const GLOBAL_CITIES: CityData[] = [
  // United States
  {
    slug: "new-york",
    name: "New York",
    country: "United States",
    countryCode: "US",
    population: 8336817,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 125,
    rentIndex: 180,
    groceriesIndex: 105,
    restaurantsIndex: 115,
    transportIndex: 95,
    utilitiesIndex: 110,
    averageNetSalary: 5500,
    averageNetSalaryGBP: 4345,
    description: "New York is one of the world's most expensive cities with unmatched opportunities.",
    highlights: ["Global finance hub", "Cultural capital", "High salaries", "Career opportunities"],
    lastUpdated: "2024-01",
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    country: "United States",
    countryCode: "US",
    population: 873965,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 130,
    rentIndex: 195,
    groceriesIndex: 108,
    restaurantsIndex: 110,
    transportIndex: 90,
    utilitiesIndex: 105,
    averageNetSalary: 7000,
    averageNetSalaryGBP: 5530,
    description: "San Francisco is the heart of global tech with the highest salaries.",
    highlights: ["Tech capital", "Highest tech salaries", "Startup culture", "Innovation hub"],
    lastUpdated: "2024-01",
  },
  {
    slug: "austin",
    name: "Austin",
    country: "United States",
    countryCode: "US",
    population: 978908,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 85,
    rentIndex: 95,
    groceriesIndex: 88,
    restaurantsIndex: 82,
    transportIndex: 75,
    utilitiesIndex: 95,
    averageNetSalary: 5000,
    averageNetSalaryGBP: 3950,
    description: "Austin offers high tech salaries with much lower costs than coastal cities.",
    highlights: ["Growing tech hub", "No state income tax", "Live music capital", "Lower costs"],
    lastUpdated: "2024-01",
  },
  {
    slug: "seattle",
    name: "Seattle",
    country: "United States",
    countryCode: "US",
    population: 737015,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 105,
    rentIndex: 135,
    groceriesIndex: 102,
    restaurantsIndex: 98,
    transportIndex: 88,
    utilitiesIndex: 98,
    averageNetSalary: 6200,
    averageNetSalaryGBP: 4898,
    description: "Seattle hosts Amazon and Microsoft headquarters with no state income tax.",
    highlights: ["Amazon & Microsoft HQ", "No state income tax", "Nature access", "Coffee culture"],
    lastUpdated: "2024-01",
  },
  // Canada
  {
    slug: "toronto",
    name: "Toronto",
    country: "Canada",
    countryCode: "CA",
    population: 2731571,
    currency: "CAD",
    currencySymbol: "C$",
    costIndex: 88,
    rentIndex: 105,
    groceriesIndex: 85,
    restaurantsIndex: 80,
    transportIndex: 82,
    utilitiesIndex: 88,
    averageNetSalary: 4500,
    averageNetSalaryGBP: 2655,
    description: "Toronto is Canada's largest city with diverse economy and multicultural population.",
    highlights: ["Multicultural hub", "Financial center", "Tech growth", "Diverse economy"],
    lastUpdated: "2024-01",
  },
  {
    slug: "vancouver",
    name: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    population: 631486,
    currency: "CAD",
    currencySymbol: "C$",
    costIndex: 92,
    rentIndex: 115,
    groceriesIndex: 88,
    restaurantsIndex: 82,
    transportIndex: 85,
    utilitiesIndex: 78,
    averageNetSalary: 4200,
    averageNetSalaryGBP: 2478,
    description: "Vancouver offers stunning nature with mild climate but expensive housing.",
    highlights: ["Mountains & ocean", "Mild climate", "Film industry", "Nature access"],
    lastUpdated: "2024-01",
  },
  {
    slug: "montreal",
    name: "Montreal",
    country: "Canada",
    countryCode: "CA",
    population: 1762949,
    currency: "CAD",
    currencySymbol: "C$",
    costIndex: 72,
    rentIndex: 65,
    groceriesIndex: 82,
    restaurantsIndex: 72,
    transportIndex: 78,
    utilitiesIndex: 75,
    averageNetSalary: 3800,
    averageNetSalaryGBP: 2242,
    description: "Montreal offers European flair with significantly lower costs.",
    highlights: ["Affordable", "French culture", "Food scene", "Creative industries"],
    lastUpdated: "2024-01",
  },
  // UAE
  {
    slug: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    population: 3400800,
    currency: "AED",
    currencySymbol: "د.إ",
    costIndex: 88,
    rentIndex: 95,
    groceriesIndex: 78,
    restaurantsIndex: 85,
    transportIndex: 65,
    utilitiesIndex: 75,
    averageNetSalary: 18000,
    averageNetSalaryGBP: 3960,
    description: "Dubai offers tax-free income with luxury lifestyle.",
    highlights: ["No income tax", "Luxury lifestyle", "Modern infrastructure", "Year-round sun"],
    lastUpdated: "2024-01",
  },
  {
    slug: "abu-dhabi",
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    population: 1450000,
    currency: "AED",
    currencySymbol: "د.إ",
    costIndex: 82,
    rentIndex: 78,
    groceriesIndex: 75,
    restaurantsIndex: 80,
    transportIndex: 60,
    utilitiesIndex: 70,
    averageNetSalary: 16000,
    averageNetSalaryGBP: 3520,
    description: "Abu Dhabi offers similar benefits to Dubai with slightly lower costs.",
    highlights: ["Tax-free", "Cultural attractions", "Slightly cheaper", "Government jobs"],
    lastUpdated: "2024-01",
  },
  // Singapore
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    population: 5454000,
    currency: "SGD",
    currencySymbol: "S$",
    costIndex: 108,
    rentIndex: 135,
    groceriesIndex: 85,
    restaurantsIndex: 75,
    transportIndex: 80,
    utilitiesIndex: 95,
    averageNetSalary: 6500,
    averageNetSalaryGBP: 3835,
    description: "Singapore offers Asian hub lifestyle with low taxes and world-class infrastructure.",
    highlights: ["Low tax rates", "Safe and clean", "Asian hub", "Excellent food"],
    lastUpdated: "2024-01",
  },
  // Australia
  {
    slug: "sydney",
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    population: 5312163,
    currency: "AUD",
    currencySymbol: "A$",
    costIndex: 102,
    rentIndex: 120,
    groceriesIndex: 95,
    restaurantsIndex: 92,
    transportIndex: 90,
    utilitiesIndex: 98,
    averageNetSalary: 6500,
    averageNetSalaryGBP: 3380,
    description: "Sydney offers iconic lifestyle with beaches and high salaries.",
    highlights: ["Beach lifestyle", "High salaries", "Iconic landmarks", "Outdoor culture"],
    lastUpdated: "2024-01",
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    population: 5078193,
    currency: "AUD",
    currencySymbol: "A$",
    costIndex: 92,
    rentIndex: 95,
    groceriesIndex: 92,
    restaurantsIndex: 88,
    transportIndex: 85,
    utilitiesIndex: 95,
    averageNetSalary: 6000,
    averageNetSalaryGBP: 3120,
    description: "Melbourne is Australia's cultural capital with excellent coffee scene.",
    highlights: ["Cultural capital", "Coffee culture", "Arts scene", "Sports hub"],
    lastUpdated: "2024-01",
  },
  {
    slug: "brisbane",
    name: "Brisbane",
    country: "Australia",
    countryCode: "AU",
    population: 2514184,
    currency: "AUD",
    currencySymbol: "A$",
    costIndex: 82,
    rentIndex: 78,
    groceriesIndex: 88,
    restaurantsIndex: 82,
    transportIndex: 80,
    utilitiesIndex: 90,
    averageNetSalary: 5500,
    averageNetSalaryGBP: 2860,
    description: "Brisbane offers subtropical lifestyle with lower costs and growing economy.",
    highlights: ["Subtropical climate", "More affordable", "Growing economy", "Relaxed lifestyle"],
    lastUpdated: "2024-01",
  },
];
