// US Cities Cost of Living Data
// Baseline: New York City = 100
import { CityData } from "./types";

export const US_CITIES: CityData[] = [
  {
    slug: "new-york",
    name: "New York City",
    country: "United States",
    countryCode: "US",
    population: 8336817,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 100, // NYC is baseline
    rentIndex: 100,
    groceriesIndex: 100,
    restaurantsIndex: 100,
    transportIndex: 100,
    utilitiesIndex: 100,
    childcareIndex: 120,
    healthcareIndex: 105,
    averageNetSalary: 5500,
    averageNetSalaryUSD: 5500,
    medianNetSalary: 4800,
    description: "New York City is America's largest city and global financial capital with unmatched career opportunities.",
    highlights: ["Global finance hub", "Cultural capital", "Excellent public transit", "Diverse industries"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 95,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 },
        { name: "Cost of Living Index (COLI)", reliability: 90 }
      ],
      sampleSize: 25000,
      confidence: 94
    },
    qualityOfLifeIndex: 75,
    safetyIndex: 72
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    country: "United States",
    countryCode: "US",
    population: 873965,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 105,
    rentIndex: 110,
    groceriesIndex: 102,
    restaurantsIndex: 105,
    transportIndex: 95,
    utilitiesIndex: 98,
    childcareIndex: 130,
    healthcareIndex: 110,
    averageNetSalary: 7000,
    averageNetSalaryUSD: 7000,
    medianNetSalary: 6200,
    description: "San Francisco is the heart of global tech with the highest salaries in the country.",
    highlights: ["Tech capital", "Highest tech salaries", "Startup culture", "Innovation hub"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 93,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 },
        { name: "Levels.fyi Salary Data", reliability: 88 }
      ],
      sampleSize: 18000,
      confidence: 92
    },
    qualityOfLifeIndex: 78,
    safetyIndex: 68
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    country: "United States",
    countryCode: "US",
    population: 3979576,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 85,
    rentIndex: 85,
    groceriesIndex: 95,
    restaurantsIndex: 90,
    transportIndex: 105,
    utilitiesIndex: 90,
    childcareIndex: 110,
    healthcareIndex: 100,
    averageNetSalary: 4800,
    averageNetSalaryUSD: 4800,
    medianNetSalary: 4200,
    description: "Los Angeles offers entertainment industry jobs and year-round sunshine at lower costs than SF or NYC.",
    highlights: ["Entertainment capital", "Great weather", "Diverse economy", "Beach lifestyle"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 92,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 22000,
      confidence: 91
    },
    qualityOfLifeIndex: 74,
    safetyIndex: 65
  },
  {
    slug: "chicago",
    name: "Chicago",
    country: "United States",
    countryCode: "US",
    population: 2746388,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 68,
    rentIndex: 55,
    groceriesIndex: 85,
    restaurantsIndex: 80,
    transportIndex: 90,
    utilitiesIndex: 95,
    childcareIndex: 95,
    healthcareIndex: 95,
    averageNetSalary: 4200,
    averageNetSalaryUSD: 4200,
    medianNetSalary: 3800,
    description: "Chicago offers big city amenities with significantly lower costs than coastal cities.",
    highlights: ["Affordable big city", "Great food scene", "Strong job market", "Excellent transit"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 91,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 19000,
      confidence: 90
    },
    qualityOfLifeIndex: 72,
    safetyIndex: 62
  },
  {
    slug: "austin",
    name: "Austin",
    country: "United States",
    countryCode: "US",
    population: 978908,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 65,
    rentIndex: 60,
    groceriesIndex: 88,
    restaurantsIndex: 85,
    transportIndex: 100,
    utilitiesIndex: 105,
    childcareIndex: 90,
    healthcareIndex: 92,
    averageNetSalary: 4500,
    averageNetSalaryUSD: 4500,
    medianNetSalary: 4000,
    description: "Austin is a booming tech hub with no state income tax and a vibrant culture.",
    highlights: ["No state income tax", "Growing tech scene", "Live music capital", "Young population"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 90,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 12000,
      confidence: 89
    },
    qualityOfLifeIndex: 80,
    safetyIndex: 75
  },
  {
    slug: "seattle",
    name: "Seattle",
    country: "United States",
    countryCode: "US",
    population: 737015,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 82,
    rentIndex: 78,
    groceriesIndex: 95,
    restaurantsIndex: 92,
    transportIndex: 88,
    utilitiesIndex: 85,
    childcareIndex: 115,
    healthcareIndex: 98,
    averageNetSalary: 5800,
    averageNetSalaryUSD: 5800,
    medianNetSalary: 5200,
    description: "Seattle offers high tech salaries with no state income tax in the Pacific Northwest.",
    highlights: ["No state income tax", "Amazon/Microsoft HQ", "Coffee culture", "Outdoor access"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 91,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 14000,
      confidence: 90
    },
    qualityOfLifeIndex: 79,
    safetyIndex: 70
  },
  {
    slug: "denver",
    name: "Denver",
    country: "United States",
    countryCode: "US",
    population: 715522,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 62,
    rentIndex: 58,
    groceriesIndex: 90,
    restaurantsIndex: 88,
    transportIndex: 95,
    utilitiesIndex: 88,
    childcareIndex: 95,
    healthcareIndex: 95,
    averageNetSalary: 4300,
    averageNetSalaryUSD: 4300,
    medianNetSalary: 3900,
    description: "Denver combines outdoor lifestyle with a growing tech scene and moderate costs.",
    highlights: ["Mountain access", "300 days sunshine", "Growing tech hub", "Active lifestyle"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 89,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 11000,
      confidence: 88
    },
    qualityOfLifeIndex: 82,
    safetyIndex: 73
  },
  {
    slug: "boston",
    name: "Boston",
    country: "United States",
    countryCode: "US",
    population: 692600,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 88,
    rentIndex: 90,
    groceriesIndex: 92,
    restaurantsIndex: 95,
    transportIndex: 85,
    utilitiesIndex: 110,
    childcareIndex: 125,
    healthcareIndex: 102,
    averageNetSalary: 5200,
    averageNetSalaryUSD: 5200,
    medianNetSalary: 4600,
    description: "Boston is a biotech and education hub with high salaries and historic charm.",
    highlights: ["Biotech/pharma hub", "Top universities", "Historic city", "Healthcare excellence"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 92,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 13000,
      confidence: 91
    },
    qualityOfLifeIndex: 77,
    safetyIndex: 71
  },
  {
    slug: "miami",
    name: "Miami",
    country: "United States",
    countryCode: "US",
    population: 467963,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 72,
    rentIndex: 75,
    groceriesIndex: 92,
    restaurantsIndex: 88,
    transportIndex: 105,
    utilitiesIndex: 95,
    childcareIndex: 100,
    healthcareIndex: 98,
    averageNetSalary: 3800,
    averageNetSalaryUSD: 3800,
    medianNetSalary: 3400,
    description: "Miami offers no state income tax, beaches, and a growing finance/tech scene.",
    highlights: ["No state income tax", "Beach lifestyle", "Latin culture", "Growing finance hub"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 88,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 10000,
      confidence: 87
    },
    qualityOfLifeIndex: 75,
    safetyIndex: 64
  },
  {
    slug: "dallas",
    name: "Dallas",
    country: "United States",
    countryCode: "US",
    population: 1304379,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 55,
    rentIndex: 50,
    groceriesIndex: 85,
    restaurantsIndex: 82,
    transportIndex: 105,
    utilitiesIndex: 98,
    childcareIndex: 88,
    healthcareIndex: 90,
    averageNetSalary: 4000,
    averageNetSalaryUSD: 4000,
    medianNetSalary: 3600,
    description: "Dallas offers affordable living with no state income tax and a strong job market.",
    highlights: ["No state income tax", "Low cost of living", "Corporate headquarters", "Affordable housing"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 90,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 15000,
      confidence: 89
    },
    qualityOfLifeIndex: 73,
    safetyIndex: 68
  },
  {
    slug: "houston",
    name: "Houston",
    country: "United States",
    countryCode: "US",
    population: 2304580,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 52,
    rentIndex: 45,
    groceriesIndex: 82,
    restaurantsIndex: 80,
    transportIndex: 108,
    utilitiesIndex: 100,
    childcareIndex: 85,
    healthcareIndex: 92,
    averageNetSalary: 3900,
    averageNetSalaryUSD: 3900,
    medianNetSalary: 3500,
    description: "Houston offers the lowest costs among major cities with no state income tax.",
    highlights: ["No state income tax", "Very affordable", "Energy sector hub", "Diverse economy"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 90,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 18000,
      confidence: 89
    },
    qualityOfLifeIndex: 70,
    safetyIndex: 62
  },
  {
    slug: "phoenix",
    name: "Phoenix",
    country: "United States",
    countryCode: "US",
    population: 1608139,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 55,
    rentIndex: 52,
    groceriesIndex: 88,
    restaurantsIndex: 85,
    transportIndex: 100,
    utilitiesIndex: 110,
    childcareIndex: 85,
    healthcareIndex: 90,
    averageNetSalary: 3600,
    averageNetSalaryUSD: 3600,
    medianNetSalary: 3200,
    description: "Phoenix offers affordable desert living with a growing tech presence.",
    highlights: ["Affordable housing", "Year-round sun", "Growing tech scene", "Low taxes"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 88,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 14000,
      confidence: 87
    },
    qualityOfLifeIndex: 72,
    safetyIndex: 66
  },
  {
    slug: "atlanta",
    name: "Atlanta",
    country: "United States",
    countryCode: "US",
    population: 498715,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 58,
    rentIndex: 55,
    groceriesIndex: 88,
    restaurantsIndex: 85,
    transportIndex: 100,
    utilitiesIndex: 95,
    childcareIndex: 92,
    healthcareIndex: 95,
    averageNetSalary: 4000,
    averageNetSalaryUSD: 4000,
    medianNetSalary: 3600,
    description: "Atlanta is a major business hub in the Southeast with affordable living.",
    highlights: ["Major business hub", "Airport connectivity", "Entertainment industry", "Affordable"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 89,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 12000,
      confidence: 88
    },
    qualityOfLifeIndex: 71,
    safetyIndex: 60
  },
  {
    slug: "washington-dc",
    name: "Washington D.C.",
    country: "United States",
    countryCode: "US",
    population: 689545,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 85,
    rentIndex: 88,
    groceriesIndex: 95,
    restaurantsIndex: 92,
    transportIndex: 85,
    utilitiesIndex: 100,
    childcareIndex: 120,
    healthcareIndex: 100,
    averageNetSalary: 5000,
    averageNetSalaryUSD: 5000,
    medianNetSalary: 4500,
    description: "Washington D.C. offers government and policy jobs with excellent public transit.",
    highlights: ["Government hub", "Great transit", "Museums/culture", "High education levels"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 91,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 11000,
      confidence: 90
    },
    qualityOfLifeIndex: 76,
    safetyIndex: 68
  },
  {
    slug: "san-diego",
    name: "San Diego",
    country: "United States",
    countryCode: "US",
    population: 1386932,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 78,
    rentIndex: 80,
    groceriesIndex: 95,
    restaurantsIndex: 90,
    transportIndex: 105,
    utilitiesIndex: 92,
    childcareIndex: 108,
    healthcareIndex: 98,
    averageNetSalary: 4400,
    averageNetSalaryUSD: 4400,
    medianNetSalary: 4000,
    description: "San Diego offers biotech jobs and perfect weather at lower costs than LA.",
    highlights: ["Perfect weather", "Biotech hub", "Beach lifestyle", "Military presence"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 89,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 13000,
      confidence: 88
    },
    qualityOfLifeIndex: 81,
    safetyIndex: 74
  },
  {
    slug: "raleigh",
    name: "Raleigh",
    country: "United States",
    countryCode: "US",
    population: 467665,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 52,
    rentIndex: 48,
    groceriesIndex: 85,
    restaurantsIndex: 82,
    transportIndex: 100,
    utilitiesIndex: 90,
    childcareIndex: 85,
    healthcareIndex: 90,
    averageNetSalary: 3800,
    averageNetSalaryUSD: 3800,
    medianNetSalary: 3400,
    description: "Raleigh offers Research Triangle jobs with excellent value for money.",
    highlights: ["Research Triangle", "Low cost of living", "Top universities", "Growing tech scene"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 88,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 9000,
      confidence: 87
    },
    qualityOfLifeIndex: 80,
    safetyIndex: 75
  },
  {
    slug: "nashville",
    name: "Nashville",
    country: "United States",
    countryCode: "US",
    population: 689447,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 55,
    rentIndex: 52,
    groceriesIndex: 88,
    restaurantsIndex: 85,
    transportIndex: 105,
    utilitiesIndex: 92,
    childcareIndex: 88,
    healthcareIndex: 95,
    averageNetSalary: 3700,
    averageNetSalaryUSD: 3700,
    medianNetSalary: 3300,
    description: "Nashville offers no state income tax with a booming economy and music scene.",
    highlights: ["No state income tax", "Music City", "Healthcare hub", "Growing economy"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 88,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 10000,
      confidence: 87
    },
    qualityOfLifeIndex: 77,
    safetyIndex: 70
  },
  {
    slug: "portland",
    name: "Portland",
    country: "United States",
    countryCode: "US",
    population: 652503,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 68,
    rentIndex: 65,
    groceriesIndex: 92,
    restaurantsIndex: 90,
    transportIndex: 85,
    utilitiesIndex: 88,
    childcareIndex: 100,
    healthcareIndex: 95,
    averageNetSalary: 4100,
    averageNetSalaryUSD: 4100,
    medianNetSalary: 3700,
    description: "Portland offers no sales tax with a creative culture and outdoor access.",
    highlights: ["No sales tax", "Creative culture", "Outdoor access", "Food scene"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 88,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 10000,
      confidence: 87
    },
    qualityOfLifeIndex: 78,
    safetyIndex: 68
  },
  {
    slug: "minneapolis",
    name: "Minneapolis",
    country: "United States",
    countryCode: "US",
    population: 429954,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 58,
    rentIndex: 52,
    groceriesIndex: 88,
    restaurantsIndex: 85,
    transportIndex: 90,
    utilitiesIndex: 95,
    childcareIndex: 95,
    healthcareIndex: 92,
    averageNetSalary: 4000,
    averageNetSalaryUSD: 4000,
    medianNetSalary: 3600,
    description: "Minneapolis offers Fortune 500 headquarters with affordable Midwest living.",
    highlights: ["Fortune 500 hub", "Lakes & parks", "Strong economy", "Affordable"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 88,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 9000,
      confidence: 87
    },
    qualityOfLifeIndex: 79,
    safetyIndex: 70
  },
  {
    slug: "salt-lake-city",
    name: "Salt Lake City",
    country: "United States",
    countryCode: "US",
    population: 199723,
    currency: "USD",
    currencySymbol: "$",
    costIndex: 55,
    rentIndex: 52,
    groceriesIndex: 88,
    restaurantsIndex: 85,
    transportIndex: 95,
    utilitiesIndex: 85,
    childcareIndex: 85,
    healthcareIndex: 90,
    averageNetSalary: 3700,
    averageNetSalaryUSD: 3700,
    medianNetSalary: 3300,
    description: "Salt Lake City offers outdoor lifestyle with a growing tech scene.",
    highlights: ["Outdoor paradise", "Growing tech hub", "Low cost of living", "Family friendly"],
    lastUpdated: "2025-01-15",
    dataVersion: "2.0.0",
    dataQuality: {
      score: 87,
      sources: [
        { name: "Bureau of Labor Statistics", reliability: 98 },
        { name: "Zillow Rent Index", reliability: 92 }
      ],
      sampleSize: 7000,
      confidence: 86
    },
    qualityOfLifeIndex: 80,
    safetyIndex: 76
  }
];
